/*
Each new term in the Fibonacci sequence is generated by adding
the previous two terms. By starting with 1 and 2, the first 10
terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values
do not exceed four million, find the sum of the even-valued
terms.
*/

#include <stdio.h>
#include <time.h>

int const MAX = 4000000;

int fib();

int main(char** args)
{
    clock_t start = clock();

    int s = 0;
    int a, i;

    for (i = 0; i < 100; i++)
        a = fib();

    printf("La suma de los terminos pares menores de 4e06 es %d\n", a);

    printf("Tiempo transcurrido: %f seg\n", ((double)clock() - start) /
            CLOCKS_PER_SEC);

    return 0;
}

int fib()
{
    int a = 0, b = 1, acum = 0, aux;

    while (a < MAX)
    {
        aux = b;
        b += a;
        a = aux;
        if (a % 2 == 0)
            acum += a;
    }

    return acum;
}

// 100 veces
// La suma de los terminos pares menores de 4e06 es 4613732
// Tiempo transcurrido: 0.000034 seg




// NO ME CONVENCE HACERLO RECURSIVO POR INEFICIENTE
// NO HACER CASO A LOS PUNTEROS DEL ACUMULADOR, PARA
// PROBAR Y NO HE CONEGUIDO QUE FUNCIONE
//
// int fib(int n, int* s)
// {
//     if (n == 0)
//     {
//         *s += 1;
//         return 1;
//     }
//     else if (n == 1)
//     {
//         *s += 1;
//         return 1;

//     }
//     else
//         return fib(n - 1, s) + fib(n - 2, s);

// }

// 4.613.732